name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build APK with Buildozer
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.11
          buildozer-cmd: buildozer init && buildozer -v android debug

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: my-android-app
          path: ./*.apk
